name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest  # FFmpeg needs Windows build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match your local Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter yt-dlp requests packaging

    - name: Download FFmpeg
      run: |
        Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z" -OutFile "ffmpeg.7z"
        7z x ffmpeg.7z -o"src/ffmpeg"
        Move-Item -Path "src/ffmpeg/ffmpeg.exe" -Destination "src/ffmpeg/ffmpeg.exe"
        Move-Item -Path "src/ffmpeg/ffprobe.exe" -Destination "src/ffmpeg/ffprobe.exe"

    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed ^
          --name "YouTube_Downloader" ^
          --add-data "src/ffmpeg/*;ffmpeg/" ^
          --add-data "src/version.txt;." ^
          --hidden-import "packaging.version" ^
          "src/main.py"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/YouTube_Downloader.exe
          src/ffmpeg/LICENSE.txt
        tag_name: ${{ github.ref }}
        generate_release_notes: true