name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup FFmpeg
      run: |
        New-Item -Path "src/ffmpeg" -ItemType Directory -Force
        Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z" -OutFile ffmpeg.7z
        7z x ffmpeg.7z -osrc/ffmpeg
        Move-Item -Path src/ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe -Destination src/ffmpeg
        Move-Item -Path src/ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffprobe.exe -Destination src/ffmpeg

    - name: Set up Python 3.10 64-bit
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.7.0  # Latest stable version
        pip install -r src/requirements.txt

    - name: Build 64-bit executable
      run: |
        $env:Path = "$env:Path;C:\Program Files\7-Zip"
        pyinstaller --noconfirm --onefile --windowed `
          --name "YouTube_Downloader" `
          --add-data "src/ffmpeg/*;ffmpeg/" `
          --add-data "src/version.txt;." `
          --hidden-import "packaging.version" `
          --hidden-import "pkg_resources.py2_warn" `
          --hidden-import "pkg_resources" `
          --hidden-import "pywin32" `
          --hidden-import "tkinter" `
          --hidden-import "customtkinter" `
          --runtime-tmpdir . `
          "src/main.py"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        files: |
          dist/YouTube_Downloader.exe
          src/ffmpeg/LICENSE.txt
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true